controlplanes:
  - name: kubespray-controlplane-1
    box: generic/ubuntu1804
    hostname: kubespray-controlplane-1
    ip: 211.183.3.200
    memory: 4096
    cpu: 4
  
workers:  
  - name: kubespray-worker-1
    box: generic/ubuntu1804
    hostname: kubespray-worker-1
    ip: 211.183.3.201
    memory: 4096
    cpu: 4
  
  - name: kubespray-worker-2
    box: generic/ubuntu1804
    hostname: kubespray-worker-2
    ip: 211.183.3.202
    memory: 4096
    cpu: 4
  
bootstrap:
  - name: kubespray-bootstrap
    box: generic/ubuntu1804
    hostname: kubespray-bootstrap
    ip: 211.183.3.203
    memory: 2048
    cpu: 2